Repository magento/magento2-sample-data, pull requests merged in 2020-05, with the labels that each got.

#144 [TR] MC-34039: Merge 2.4-develop into 2.4-develop-php74
  app/code/Magento/TaxSampleData/Test/Model/TaxTest.php
Labels: 2.4-develop-php74

#152 [TSG] Fixes for 2.4 (pr37) (2.4-develop)
  README.md
Labels: 2.4-develop: dep

#151 [TR]: MySQL8 Support
  app/code/Magento/ReviewSampleData/Model/Review.php
Labels: 2.4-develop: dep

#153 [TR]: MySQL8 Support
  app/code/Magento/ReviewSampleData/Model/Review.php
Labels: 2.4-develop: :two:

#150 [Pangolin] Remove MTF Tests and related code from Magento 2.4
  dev/tests/functional/tests/app/Magento/BundleSampleData/Test/TestCase/NavigateBundleEntityTest.php
  dev/tests/functional/tests/app/Magento/BundleSampleData/Test/TestCase/NavigateBundleEntityTest.xml
  dev/tests/functional/tests/app/Magento/CatalogSampleData/Test/TestCase/NavigateProductEntityTest.php
  dev/tests/functional/tests/app/Magento/CatalogSampleData/Test/TestCase/NavigateProductEntityTest.xml
  dev/tests/functional/tests/app/Magento/ConfigurableSampleData/Test/TestCase/NavigateConfigurableProductEntityTest.php
  dev/tests/functional/tests/app/Magento/ConfigurableSampleData/Test/TestCase/NavigateConfigurableProductEntityTest.xml
  dev/tests/functional/tests/app/Magento/CustomerSampleData/Test/Constraint/AssertCustomerNavigation.php
  dev/tests/functional/tests/app/Magento/CustomerSampleData/Test/TestCase/LoginCustomerTest.php
  dev/tests/functional/tests/app/Magento/CustomerSampleData/Test/TestCase/LoginCustomerTest.xml
  dev/tests/functional/tests/app/Magento/DownloadableSampleData/Test/TestCase/NavigateDownloadableProductEntityTest.php
  dev/tests/functional/tests/app/Magento/DownloadableSampleData/Test/TestCase/NavigateDownloadableProductEntityTest.xml
  dev/tests/functional/tests/app/Magento/GroupedProductSampleData/Test/TestCase/NavigateGroupedProductEntityTest.php
  dev/tests/functional/tests/app/Magento/GroupedProductSampleData/Test/TestCase/NavigateGroupedProductEntityTest.xml
  dev/tests/functional/tests/app/Magento/SalesSampleData/Test/TestCase/CheckoutSalesSampleDataProductEntityTest.php
  dev/tests/functional/tests/app/Magento/SalesSampleData/Test/TestCase/CheckoutSalesSampleDataProductEntityTest.xml
  dev/tests/functional/tests/app/Magento/SalesSampleData/Test/etc/testcase.xml
  dev/tests/functional/testsuites/Magento/Mtf/TestSuite/InjectableTests/mysql_search.xml
  dev/tests/functional/testsuites/Magento/Mtf/TestSuite/InjectableTests/sample-data-with-installation.xml
  dev/tests/functional/testsuites/Magento/Mtf/TestSuite/InjectableTests/sample-data.xml
Labels: 2.4-develop: dep
